package com.dell.treasure.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK".
*/
public class TaskDao extends AbstractDao<Task, Long> {

    public static final String TABLENAME = "TASK";

    public TaskDao(DaoConfig config) {
        super(config);
    }


    public TaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }
    
    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LAST_ID\" TEXT," + // 1: lastId
                "\"TASK_ID\" TEXT UNIQUE ," + // 2: taskId
                "\"TARGET_BLE\" TEXT," + // 3: targetBle
                "\"START_TIME\" TEXT," + // 4: startTime
                "\"BEGIN_TIME\" TEXT," + // 5: beginTime
                "\"LENGTH\" REAL NOT NULL ," + // 6: length
                "\"DISTANCE\" TEXT," + // 7: distance
                "\"NEED_NUM\" TEXT," + // 8: needNum
                "\"CURRENT_NUM\" TEXT," + // 9: currentNum
                "\"CURRENT_LEVEL\" TEXT," + // 10: currentLevel
                "\"MONEY\" TEXT," + // 11: money
                "\"FLAG\" INTEGER NOT NULL );"); // 12: flag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Task entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String lastId = entity.getLastId();
        if (lastId != null) {
            stmt.bindString(2, lastId);
        }

        String taskId = entity.getTaskId();
        if (taskId != null) {
            stmt.bindString(3, taskId);
        }

        String targetBle = entity.getTargetBle();
        if (targetBle != null) {
            stmt.bindString(4, targetBle);
        }

        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(5, startTime);
        }

        String beginTime = entity.getBeginTime();
        if (beginTime != null) {
            stmt.bindString(6, beginTime);
        }
        stmt.bindDouble(7, entity.getLength());

        String distance = entity.getDistance();
        if (distance != null) {
            stmt.bindString(8, distance);
        }

        String needNum = entity.getNeedNum();
        if (needNum != null) {
            stmt.bindString(9, needNum);
        }

        String currentNum = entity.getCurrentNum();
        if (currentNum != null) {
            stmt.bindString(10, currentNum);
        }

        String currentLevel = entity.getCurrentLevel();
        if (currentLevel != null) {
            stmt.bindString(11, currentLevel);
        }

        String money = entity.getMoney();
        if (money != null) {
            stmt.bindString(12, money);
        }
        stmt.bindLong(13, entity.getFlag());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Task entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String lastId = entity.getLastId();
        if (lastId != null) {
            stmt.bindString(2, lastId);
        }

        String taskId = entity.getTaskId();
        if (taskId != null) {
            stmt.bindString(3, taskId);
        }

        String targetBle = entity.getTargetBle();
        if (targetBle != null) {
            stmt.bindString(4, targetBle);
        }

        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(5, startTime);
        }

        String beginTime = entity.getBeginTime();
        if (beginTime != null) {
            stmt.bindString(6, beginTime);
        }
        stmt.bindDouble(7, entity.getLength());

        String distance = entity.getDistance();
        if (distance != null) {
            stmt.bindString(8, distance);
        }

        String needNum = entity.getNeedNum();
        if (needNum != null) {
            stmt.bindString(9, needNum);
        }

        String currentNum = entity.getCurrentNum();
        if (currentNum != null) {
            stmt.bindString(10, currentNum);
        }

        String currentLevel = entity.getCurrentLevel();
        if (currentLevel != null) {
            stmt.bindString(11, currentLevel);
        }

        String money = entity.getMoney();
        if (money != null) {
            stmt.bindString(12, money);
        }
        stmt.bindLong(13, entity.getFlag());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public Task readEntity(Cursor cursor, int offset) {
        Task entity = new Task( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // lastId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // taskId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // targetBle
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // startTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // beginTime
            cursor.getDouble(offset + 6), // length
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // distance
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // needNum
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // currentNum
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // currentLevel
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // money
            cursor.getInt(offset + 12) // flag
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, Task entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLastId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTaskId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTargetBle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStartTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBeginTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLength(cursor.getDouble(offset + 6));
        entity.setDistance(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setNeedNum(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCurrentNum(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCurrentLevel(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setMoney(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setFlag(cursor.getInt(offset + 12));
     }
     
    @Override
    protected final Long updateKeyAfterInsert(Task entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Task entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }
    
    @Override
    public boolean hasKey(Task entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity Task.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LastId = new Property(1, String.class, "lastId", false, "LAST_ID");
        public final static Property TaskId = new Property(2, String.class, "taskId", false, "TASK_ID");
        public final static Property TargetBle = new Property(3, String.class, "targetBle", false, "TARGET_BLE");
        public final static Property StartTime = new Property(4, String.class, "startTime", false, "START_TIME");
        public final static Property BeginTime = new Property(5, String.class, "beginTime", false, "BEGIN_TIME");
        public final static Property Length = new Property(6, double.class, "length", false, "LENGTH");
        public final static Property Distance = new Property(7, String.class, "distance", false, "DISTANCE");
        public final static Property NeedNum = new Property(8, String.class, "needNum", false, "NEED_NUM");
        public final static Property CurrentNum = new Property(9, String.class, "currentNum", false, "CURRENT_NUM");
        public final static Property CurrentLevel = new Property(10, String.class, "currentLevel", false, "CURRENT_LEVEL");
        public final static Property Money = new Property(11, String.class, "money", false, "MONEY");
        public final static Property Flag = new Property(12, int.class, "flag", false, "FLAG");
    }
    
}
